behaviors:
  PlayerLearning:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024       # Aumentado para maior estabilidade
      buffer_size: 10240      # 10x o batch_size, uma boa proporção
      learning_rate: 3.0e-4
      beta: 5.0e-3          # Aumentar um pouco a entropia pode ajudar na exploração inicial
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear # ou constant

    network_settings:
      normalize: true
      hidden_units: 256     # Uma rede um pouco maior pode capturar mais complexidade
      num_layers: 2

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    max_steps: 1000000      # 1 milhão de passos. Um ponto de partida muito melhor. Espere treinos de 30min a algumas horas.
    time_horizon: 128       # Um horizonte maior permite ao agente planejar mais a longo prazo
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 100000